baseURL: "https://david-balut.github.io/"
title: David Bałut
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: News
          url: news/
          weight: 2
        - name: Talks
          url: talks/
          weight: 3
        - name: Fun
          url: fun/
          weight: 4

params:
    description: "Personal website of David Bałut, physics student at the University of Illinois Urbana-Champaign interested in many-body physics."
    author: David Bałut
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","news"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: David Bałut
          subtitle: "I am a physics undergrad at the University of Illinois Urbana-Champaign, working with the groups of Peter Abbamonte and Barry Bradlyn. I am generally interested in condensed matter theory and many-body theory. I will be starting an MPhil in Physics at Cambridge in the fall, working with Professor Claudio Castelnovo."
          imageUrl: "profile.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: News
              url: news/
            - name: Talks
              url: talks/
            - name: Fun
              url: fun/

    socialIcons:
        - name: Email
          url: mailto:davidbalut@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=3pZLDeAAAAAJ
        - name: CV
          url: cv.pdf

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "David Bałut"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2